import { FC } from "react";
import Head from "next/head";
import { iMainLayoutProps } from "./types";

const MainLayout: FC<iMainLayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Navbar Here */}
        {children}
        {/* Footer Here */}
      </main>
    </>
  );
};

export default MainLayout;
