import Head from 'next/head';
import Image from "next/image";
// import Link from 'next/link';
// import '../styles/event.css';

export default function Event() {
  return (
    <>
      <Head>
        <title>Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="wrapper">
          <div className='top-decoration'>
            <div className='left-decoration' style={{ width: '100px', height: '140px' }}>
              <Image width={220} height={150} src='/images/top-balon-left.png' />
            </div>
            <div className='right-decoration' style={{ width: '100px', height: '140px' }}>
              <Image width={220} height={150} src='/images/top-balon-left.png' />
            </div>
          </div>
          <div className='section'>
            <div className='section-top'>
              xxxx
            </div>
            <div className='section-mid'>
              xxxx
            </div>
            <div className='section-bottom'>
              xxx
              {/* <Link className='button-invitation' href="/event">Lihat Detail Acara</Link> */}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
