import Head from 'next/head';
import Image from "next/image";
import Link from 'next/link';
import '../styles/first.css';
import { useSearchParams } from 'next/navigation'

export default function First() {
  const searchParams = useSearchParams()
  const name = searchParams.get('name')
  return (
    <>
      <Head>
        <title>First</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="wrapper">
          <div className='top-decoration'>
            <div className='left-decoration' style={{ width: '100px', height: '140px' }}>
              <Image width={220} height={150} src='/images/top-balon-left.png' />
            </div>
            <div className='right-decoration' style={{ width: '100px', height: '140px' }}>
              <Image width={220} height={150} src='/images/top-balon-left.png' />
            </div>
          </div>
          <div className='section'>
            <div className='section-top'>
              <div className='leaf-left'>
                <Image width={170} height={150} src='/images/leaf-left-first-page.png' />
              </div>
              <h1 className='callname'>Greesa</h1>
              <h2 className='fullname'>Anna Greesa Liora</h2>
              <h2 className='is-turning'>is turning 2</h2>
              <h2 className='birth-date'>October 23, 2023</h2>
            </div>
            <div className='section-mid'>
              <div className='leaf-right'>
                <Image width={170} height={150} src='/images/leaf-right-first-page.png' />
              </div>
              <div className='wrapper-image'>
                <Image width={450} height={450} src='/images/gica-tiduran.png' />
              </div>
            </div>
            <div className='section-bottom decrement-top-margin-50'>
              <Link className='button-invitation' href={`/event?name=${name}`}>Lihat Detail Acara</Link>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
